### ISSUE TITLE
Jest

### ISSUE THREAD

**Issue by DanielFerrariR** [developit/workerize-loader#103]
Even with the steps from https://github.com/developit/workerize-loader#testing (creating workerize-jest.js file and adding it to transform section of jest config), seems like Jest still can't understand my 'workerize-loader!' imports.

Versions

```
"workerize-loader": "^1.2.1"
"jest": "^25.5.4"
```

Any idea, why?

**Comment by paulmelero** [comment]
Me too, I'm getting ` Cannot find module 'workerize-loader!...'`

**Comment by noseworthy** [comment]
Following the the instructions in #107 solved this for me!

**Comment by developit** [comment]
I merged and revised the instructions from #107. Cheers!
