### ISSUE TITLE
importScripts

### ISSUE THREAD

**Issue by OhFlohre** [developit/workerize-loader#104]
is there a way to use the WorkerGlobalScope.importScripts() method with workerize-loader?

**Comment by DronHazra** [comment]
I'd like to know this too

**Comment by wclr** [comment]
why not `self.importScripts`?

**Comment by developit** [comment]
Indeed - the existence of `importScripts` just depends on how you load the module. If it's a Classic Worker (`new Worker(url)`), importScripts() should work fine. If it's a Module Worker (`new Worker(url, {type:'module'})`), you'll want to use `import()` instead.

Read more here: https://web.dev/module-workers/

(I get the impression this question was prompted by TypeScript making it seem like `importScripts()` isn't defined - TypeScript doesn't know that you're in a Worker context unless you tell it you are, which requires moving your worker code into a directory with its own `tsconfig.js` that replaces DOM typings with Worker ones. It's... a rough edge)
