### ISSUE TITLE
How to make the output worker js file under /static rather than root directory in Create React App?

### ISSUE THREAD

**Issue by sep2** [developit/workerize-loader#112]
Create React App will bundle all the js files under a `/static` folder, which makes CDN cache easier, but the workerize-loader will output the `hash.worker.js` file under the root `/` path, how can I change that? Do I need to eject CRA?

**Comment by developit** [comment]
You can set the [`name` option](https://github.com/developit/workerize-loader#name):

```js
import worker from 'workerize-loader?name=static/[hash]!./path-to-worker.js';
```
