### ISSUE TITLE
Handling callbacks from worker to main thread

### ISSUE THREAD

**Issue by TripleSpeeder** [developit/workerize-loader#21]
I like this approach, it makes handling tasks for webworkers really easy! However I'm missing one thing - How can I handle callbacks from the worker thread back to the main thread? This is necessary for example when the worker wants to provide some progress info to the main thread.

Any opinions on this? I could imagine a somehow "reverse" setup, where the webworker can access functions of the main thread in a similar way like the main thread calls functions of the webworker.

**Comment by developit** [comment]
You can use this lib to execute javascript/functions on the main thread from your worker context:
https://gist.github.com/developit/cddb634cd742a821d898c4c6e71d6607
