### ISSUE TITLE
How to handle blob data?

### ISSUE THREAD

**Issue by MartinBucko** [developit/workerize-loader#23]
I don't cant find solution to handle blob file data sended to worker. Its possible?

My object sended to worker:

```
{
id: 'jnakjnkjnkdjnkd',
item: {},
blob: Blob
}
```

Blob have no file content in worker, just type and size.
Thanks! :)

**Comment by developit** [comment]
Read the blob into an arraybuffer:
https://stackoverflow.com/a/15981017/194340
