### ISSUE TITLE
is not a function

### ISSUE THREAD

**Issue by 0m15** [developit/workerize-loader#32]
I just tried it with webpack-blocks, however I can't get it to run:

```
// worker.js
export function foo() { return 1; }

// index.js
import worker from 'workerize-loader!./worker'
const inst = worker()
inst.foo()

Uncaught TypeError: inst.foo is not a function
```

Is there something am I missing?

**Comment by HZSamir** [comment]
Having the same issue here

**Comment by janbaykara** [comment]
I find I have to restart webpack when I change the worker module. It only recognises the first time it builds; this may have something to do with hot-reloading. (#24)

**Comment by kontrollanten** [comment]
Same here, it won't work even after restarting webpack either

**Comment by Heliodromel** [comment]
Hi, did you guys find out any solution or explanation about this ?

**Comment by HZSamir** [comment]
@Heliodromel So far, no. Went back to using vanilla workers for now.

**Comment by Heliodromel** [comment]
Ok thanks.
Looks like there is something wrong with `var methods = ${JSON.stringify(exports)}` in `index.js`
After building, i get `methods = []` when i check my worker script in dev tools

**Comment by Heliodromel** [comment]
Actually, looking a bit futher and logging : 
```
var exports = Object.keys(CACHE[worker.file] = compilation.__workerizeExports || CACHE[worker.file] || {});
```
gives `[]` to me.
The parser is not detecting exports : `parser.plugin('export declaration', function (expr) {` is not fired.

I tried with webpack 3.2 and webpack 3.11 and also tried workerize-loader 1.0.1 and 1.0.2. I'm always experimenting the problem. I don't know if it matters but i also have a babel-loader in my webpack config.

**Comment by Heliodromel** [comment]
I dug a bit and it looks like to be linked to babel. Babel converts import/export to commonjs standards. As a consequence it seems that the parser is not seeing the export declaration. If i add { modules: false } in my babel config, the loader starts working again :
```
rules: [
            {
                test: /\.js$/,
                exclude: /(node_modules)/,
                loader: "babel-loader",
                options: {
                    presets: [
                        [
                            "env",
                            {
                                modules: false,
                            },
                        ],
```

**Comment by developit** [comment]
We should update the README to recommend disabling Babel's CommonJS transform. @Heliodromel - want to add your suggestion as documentation? :)

**Comment by Heliodromel** [comment]
Yep sure, i'll create a PR with that.

**Comment by developit** [comment]
For anyone finding this issue when searching, please see the solution here:
https://github.com/developit/workerize-loader#about-babel

**Comment by exarus** [comment]
@developit I'm still facing issue, even if my babel module transpilation is off.
It seems that issue is related to HMR. I'll try to describe my enviroment so that you could suggest where we may start bug detection.

I'm using vue-cli@2 ["webpack"](https://github.com/vuejs-templates/webpack) template (it's Vue version of create-react-app, but already ejected).

Used workerize loader like that:
`src/my.js`
```
import MyWorker from 'workerize-loader!./MyWorker';
const worker = new MyWorker();
```
No changes to default [webpack config](https://github.com/vuejs-templates/webpack/blob/develop/template/build/webpack.dev.conf.js) were made

`.babelrc`
```json
{
  "presets": [
    ["env", {
      "modules": false,
      "useBuiltIns": true
    }],
    "stage-2"
  ],
  "plugins": ["transform-vue-jsx", "transform-runtime"],
}
```

In some time after few HMR updates MyWorker constructor always returns:
`Worker {onmessage: null, onerror: null}`

Hope that can help to identify issue. In near future I'll try to create a repository that reproduces the issue.

**Comment by developit** [comment]
AFAIK this is a duplicate of #24. Right now this loader doesn't output anything special for handling HMR, so eventually the module exports it proxied to your main thread become invalid or get reclaimed.

The solution would be to detect when Webpack is in dev mode (or when it has HMR enabled?) and inject something like this:

```js
if (module.hot) {
  module.hot.accept(['./worker-entry-url-here'], () => {
    __webpack_exports__ = require('./worker-entry-url-here')
  });
}
```

**Comment by exarus** [comment]
@developit then it makes sense to add your suggestion to #24 . Gonna test it out, thanks.

**Comment by exarus** [comment]
Ok, my use case is import `help.worker.js` to `index.js`
index.js
```js
import help from 'workerize-loader!./help.worker';

if (module.hot) {
  module.hot.accept(['./workerize-loader!./help.worker'], () => {
    // eslint-disable-next-line
    __webpack_exports__ = require('workerize-loader!./help.worker')
  });
}
```
This piece seems to be hm... strange.
As far as I understand __webpack_exports__ is variable in module scope. i.e. `__webpack_exports__` belong to worker file. and I can't reference it in arrow function in `index.js`.
I might be wrong, correct me if I do.
Unfortunately, I'm not an expert in webpack internals. Any help is welcome.

**Comment by aeroxy** [comment]
I am using react-script typescript and it happens to me as well, but there is no way to disable bable it seems...
