### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by hronro** [developit/workerize-loader#35]
I got this error when I upgrade webpack to v4
![image](https://user-images.githubusercontent.com/15059605/39116520-43c3f79a-4717-11e8-8256-92c1037f30ab.png)
![image](https://user-images.githubusercontent.com/15059605/39116564-5d83a37e-4717-11e8-9b3f-b271ff3bf91e.png)

**Comment by hronro** [comment]
It seems like this is caused by webpack hot reload: https://github.com/webpack/webpack/issues/6642

**Comment by developit** [comment]
Should be fixed in Webpack soon.

**Comment by developit** [comment]
For now I've made workerize-loader detect when `output.globalObject` is set to `window`, and it will simply show a warning and recommend setting it to `self` or `this`.

**Comment by ss-bb** [comment]
Sorry to comment on a close issue, But I have the exact same error than above on the latest branch. 

I'm using it in a vueJs component. Could it cause the Problem ?

I basically copy paste the code from exemple, add 2 console.log -> 
                let instance = worker();
                console.log('wut');
                let page = instance.burnCpu(1000);
                console.log('res',page);

![pb-worker](https://user-images.githubusercontent.com/5887682/46068096-ad263a00-c178-11e8-994a-f9203b66d372.png)

**Comment by bidiu** [comment]
What should I do if I am using `create-react-app` without ejecting (I don't have access to the config file of Webpack)? Just upgraded to `react-script` 2.0+, it starts to break.

**Comment by developit** [comment]
@bidiu - can you file an issue with create-react-app? They should be using `self` as the default.

**Comment by bidiu** [comment]
@developit Thanks!

**Comment by bknill** [comment]
You can use react-app-rewired with   config.output.globalObject= `self` in the config-overrides in a CRA to change this
