### ISSUE TITLE
Support for async functions inside workers?

### ISSUE THREAD

**Issue by fnlctrl** [developit/workerize-loader#46]
I get the following error
```
Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': Response object could not be cloned.
```
for 
```
let instance = worker() 
instance.functionReturningAPromise().then(...)
```
due to the fact that Promises can't be cloned.

**Comment by fnlctrl** [comment]
Oops, my mistake, it was actually the Response object rather than a Promise. Sorry for the noise.

**Comment by Jared-Dahlke** [comment]
can you explain this @fnlctrl , I'm getting the same error and can't figure out why
