### ISSUE TITLE
Integration with Create React App

### ISSUE THREAD

**Issue by craigcoles** [developit/workerize-loader#5]
I need to setup a worker in CRA. I have ejected CRA, so I can add the loader via Webpack configs. 

However, I am not sure I am doing this correctly. I have been using the [test/webpack.config.js](https://github.com/developit/workerize-loader/blob/master/test/webpack.config.js) as a helper. The only thing I noticed that was different, was the resolveLoader section in the webpack config. Have I missed something else?

Current config:

```js
module.exports = {
  ...
  resolveLoader: {
    alias: {
      'workerize-loader': path.resolve(__dirname, 'workerize-loader')
    }
  },
  ...
};
```

**Comment by developit** [comment]
Hmm - you shouldn't need any resolution config at all to use this.

```sh
npm i -D workerize-loader
```

```js
import worker from 'workerize-loader!./foo';
```

**Comment by craigcoles** [comment]
I did try that, but CRA has rules setup:

```
Unexpected '!' in 'workerize-loader!Workers/Worker'. Do not use import syntax to configure webpack loaders
```

**Comment by developit** [comment]
Eek! That's a surprisingly draconian lint rule.. maybe try with require?

```js
const worker = require('workerize-loader!Workers/Worker')
```

**Comment by ddebarros** [comment]
CRA uses eslint so just suppress that rule for the import line.


```javascript
import worker from 'workerize-loader!./foo'; // eslint-disable-line import/no-webpack-loader-syntax
```

**Comment by developit** [comment]
Perfect! Thanks for the tip, closing this issue then.

**Comment by talolard** [comment]
closed by 271e6926e1d26d1b5de98462ad5161a2c838e2f8

**Comment by kentcdodds** [comment]
Related: https://github.com/facebook/create-react-app/issues/7741

**Comment by wilcoxmd** [comment]
Has anyone gotten workerize-loader to work with create-react-app and typescript? 

I'm using react-scripts version 3.2, so should have the PR related to [facebook/create-react-app#7741](https://github.com/facebook/create-react-app/issues/7741) included in my build. However, I keep running into a typescript error: `Cannot find module 'workerize-loader!./example.worker'.`

I'm importing like so: 
```typescript
// in ./Component.tsx
import ExampleWorker from 'workerize-loader!./example.worker'; // eslint-disable-line import/no-webpack-loader-syntax

// ./example.worker.ts
interface IWorkerMessage {
  message: string;
  time: number;
}

export const sayHi = async ({ message, time }: IWorkerMessage) => {
  console.log('in worker function!, got message, ', message);
  const start = Date.now();
  let count: number = 0;
  while (Date.now() - start < time) {
    count++;
  }
  return count;
};

```




Anyone else seen this error / overcome it?

**Comment by stevenmcdonald** [comment]
@wilcoxmd 
It's not pretty, but I was able to get it to work using a shim js file to load the worker and export it to the TS file:

``` javascript
// in ./ComponentWorkerShim.js
import ExampleWorker from 'workerize-loader!./example.worker'; // eslint-disable-line import/no-webpack-loader-syntax

export default ExampleWorker
```

```typescript
// in ./Component.tsx
import ExampleWorker from './ComponentWorkerShim';

// ...
```

Then you have type issues to deal with when calling the worker, but at least it works.

**Comment by MikeSpitz** [comment]
The above comment works great but I'm running into issues with jest when I use the shim. Without the shim jest works fine but typescript doesn't 😢 

**Edit**
I was able to get this running without the shim by using require:

Component.tsx
```
const Worker = require( "workerize-loader!../../workers/workerFileName"); // eslint-disable-line import/no-webpack-loader-syntax
```

src/workers/workerFileName.js
```
export async function doStuff(data) {
    // Worker code here
}
```

package.json
```
jest {
     "moduleNameMapper": {
       "workerize-loader!../../workers/workerFileName":"<rootDir>/src/workers/workerFileName.mock.js"
    },
}
```

src/workers/workerFileName.mock.js
```
class WorkerFileName {

}

module.exports = WorkerFileName;
```

Now I have the following:
* Workers work in create-react-app with typescript
* Components that include the workerize-loader file no longer fail in jest

**Comment by wilcoxmd** [comment]
I think I found another solution here as well, by using a hook for each worker I create. Using some of your tips above about the jest config, and some tips from [here](https://github.com/developit/workerize-loader/issues/3#issuecomment-538730979), I have the following that works for me and allows typed usage:

src/workers/sampleWorker.worker.ts
```javascript
export function foo(a: number, b: number) {
  return `Worker result: ${a + b}`;
}
```

src/workers/workerDeclarations.d.ts 
```javascript
declare module 'workerize-loader!*' {
  type AnyFunction = (...args: any[]) => any;
  type Async<F extends AnyFunction> = (
    ...args: Parameters<F>
  ) => Promise<ReturnType<F>>;

  type Workerized<T> = Worker &
    { [K in keyof T]: T[K] extends AnyFunction ? Async<T[K]> : never };

  function createInstance<T>(): Workerized<T>;
  export = createInstance;
}
```

src/hooks/useSampleWorker.ts
```javascript
// eslint-disable-next-line import/no-webpack-loader-syntax
import createWorker from 'workerize-loader!../workers/sampleWorker.worker';
import * as SampleWorker from '../workers/sampleWorker.worker';

const sampleWorker = createWorker<typeof SampleWorker>();

export const useSampleWorker = () => sampleWorker;
```

Component.tsx
```javascript
import {useSampleWorker} from '../hooks/useSampleWorker';

function Component(props) { 
    const sampleWorker = useSampleWorker();
    
    // ...
    sampleWorker.foo(1000, 1000).then(result => console.log(result)) // result is of type 'string'
}
```

then to make tests work.... 
src/workers/mocks/sampleWorker.mock.ts
```javascript
import { foo } from '../sampleWorker.worker';

export default () => ({
  foo,
});
```

package.json 
```json
"jest": {
    "moduleNameMapper": {
      "workerize-loader!../workers/sampleWorker.worker": "<rootDir>/src/workers/mocks/sampleWorker.mock.ts"
    }
}
```

**Comment by kentcdodds** [comment]
Awesome. Instead of `moduleNameMapper` I'd probably just do `jest.mock`. Glad you got that working and thanks for coming back here to show us how you did it.

**Comment by wilcoxmd** [comment]
@kentcdodds No problem! This one has bugged me for a bit because I've really wanted to use this package :) 

I had a little trouble getting `jest.mock` to work for me. What were you picturing? If I try to use `jest.mock` in my tests I was getting more 'unresolved' module errors. 

An alternative, more flexible option I did think of though is to better use the regex in the `moduleNameMapper`.... 

```json
  "jest": {
    "moduleNameMapper": {
      "^workerize-loader!(.*)/workers(.*)": "<rootDir>/src/workers/__mocks__$2"
    }
  }
```

and to make the actual mock file more easy to work with...
in `src/workers/__mocks__/sampleWorker.worker.ts`
```javascript
import * as SampleWorker from '../sampleWorker.worker';

export default () => SampleWorker
```

That way any worker you add into the `/workers` directory just needs a corresponding mock like the one above and you shouldn't really have to touch it again?

**Comment by aeroxy** [comment]
Cannot find module 'workerize-loader!./workerize'.ts(2307)

TypeScript also doesn't like it.

**Comment by Download** [comment]
> CRA uses eslint so just suppress that rule for the import line.

When I do, it works in development.
However when I then build the project, it fails without errors. It just doesn't generate anything.
Took me a few hours to figure out why.
Uncommenting the workerize loader import fixed the build right away.
So think twice before using this.

**Comment by lukesmurray** [comment]
> src/workers/workerDeclarations.d.ts
> 
> declare module 'workerize-loader!*' {
>   type AnyFunction = (...args: any[]) => any;
>   type Async<F extends AnyFunction> = (
>     ...args: Parameters<F>
>   ) => Promise<ReturnType<F>>;
> 
>   type Workerized<T> = Worker &
>     { [K in keyof T]: T[K] extends AnyFunction ? Async<T[K]> : never };
> 
>   function createInstance<T>(): Workerized<T>;
>   export = createInstance;
> }

Using a flattened promise so async methods aren't double nested as `Promise<Promise<return value>>`

```ts
declare module "workerize-loader!*" {
  type FlattenedPromise<T> = unknown extends T
    ? Promise<T>
    : T extends Promise<infer U>
    ? T
    : Promise<T>;

  type AnyFunction = (...args: any[]) => any;
  type Async<F extends AnyFunction> = (
    ...args: Parameters<F>
  ) => FlattenedPromise<ReturnType<F>>;

  type Workerized<T> = Worker &
    { [K in keyof T]: T[K] extends AnyFunction ? Async<T[K]> : never };

  function createInstance<T>(): Workerized<T>;
  export = createInstance;
}

```

**Comment by rdgfuentes** [comment]
Fixed it following @wilcoxmd's [solution described above](https://github.com/developit/workerize-loader/issues/5#issuecomment-570663710) and also applied the [alternative option](https://github.com/developit/workerize-loader/issues/5#issuecomment-570706868) but with a slightly tweak in the `moduleNameMapper` regexp :
```json

  "jest": {
    "moduleNameMapper": {
      "^workerize-loader(\\?.*)?!(.*)/([^/]*)$": "$2/__mocks__/$3"
    }
  }
```
with the purpose of loading mocks from a file with the same name that the worker but located in the `./__mocks__` folder where the worker file is (Eg: `<workerFolder>/__mocks__/<workerFilename>`) since we want to have the workers and its mocks next to the other files organized by features. Our files structure looks like this:

```
├── src/
│   └── features/
│       └── foo/
│           ├── FooBar.worker.ts 
│           └── __mocks__
│               └── FooBar.worker.ts
├── App.tsx
└── App.test.tsx
```
