### ISSUE TITLE
Enable tree-shaking 

### ISSUE THREAD

**Issue by feyzo** [developit/workerize-loader#50]
I have used `workerize-loader` for a small web worker implementation and it worked great! I ran into trouble once i started importing helper utility functions which ended up bundling almost the entire project.

I want to add tree shaking ability in order to:
1- Reduce bundle size
2- Prevent importing unused code which may contain code `window.location..` etc.

Can you point me towards a direction so i can make a PR?

Thanks

**Comment by developit** [comment]
That would be very nice!  I think the only way to have tree-shaking work here would be to keep track of which functions are used in the parent (non-worker) scope, remove any of the exports for unused ones in the child (worker) scope.  That would involve writing a Webpack parser plugin, which can be a little tricky.

**Comment by qm3ster** [comment]
Not exporting things you don't want to include in the outermost worker module seems very easy.
Is there a case when this is difficult, @feyzo ?

**Comment by developit** [comment]
I'm going to close this one out, since Webpack itself doesn't support tree shaking across async module boundaries (like dynamic import). Doing so would be going quite a bit beyond what Webpack's core is capable of, it would be better to wait and use something built-in once that arrives.
