### ISSUE TITLE
is it suppoting web workers in non-ejected CRA?

### ISSUE THREAD

**Issue by subhranshudas** [developit/workerize-loader#58]
Does workerize support usage of web workers in CRA?

Thanks.

**Comment by Cakaaa** [comment]
I would really like to know as well 👍

**Comment by developit** [comment]
The only reason why this wouldn't work is if CRA specifically prevents the use of Webpack's inline loader syntax.  Angular CLI does this and is unconfigurable like CRA - in those cases there is no way to use workerize-loader.

**Comment by nicolas-zozol** [comment]
In the above example, I would add to avoid eslint failure:

`import { foo } from 'workerize-loader!./foo';: // eslint-disable-line import/no-webpack-loader-syntax`
