### ISSUE TITLE
Warning (workerize-loader): output.globalObject is set to "window". It should be set to "self" or "this" to support HMR in Workers.

### ISSUE THREAD

**Issue by wujekbogdan** [developit/workerize-loader#59]
I'm getting the following warning when building a Vue.js app in production mode:

> Building for production...Warning (workerize-loader): output.globalObject is set to "window". It should be set to "self" or "this" to support HMR in Workers.

 The app is set up using the [official Vue CLI tool](https://cli.vuejs.org/).

**Comment by koalalorenzo** [comment]
I am having the same issue with TypeScript, React and Webpack

**Comment by koalalorenzo** [comment]
@developit is this project still maintained?

**Comment by stoplion** [comment]
having same issue

**Comment by bsherrill480** [comment]
Found the solution in https://github.com/developit/workerize-loader/issues/35

It seems that for HMR (Hot Module Replacement), you need to change your babel config a bit. You need to set globalObject to 'this' (https://webpack.js.org/configuration/output#outputglobalobject).

To do so, find your webpack file (something like `webpack.config.js`) and add:

```
module.exports = {
  // ...
  output: {
    // ...
    globalObject: 'this'
  }
};
```

**Comment by developit** [comment]
Right - the solution here is to do exactly what that intentional warning says. If you get the warning and care about HMR, do what the warning says as @bsherrill480 has explained here.

**Comment by xerosanyam** [comment]
Thanks, for future readers using Vue cli.

solved this by https://github.com/vuejs/vue-cli/issues/2276#issuecomment-414265234

**Comment by developit** [comment]
Awesome - thanks for the update. I'm going to close this out now, since it looks like `vue-cli` actually switched to using `self` by default in vuejs/vue-cli#2286 (yay!).
