### ISSUE TITLE
Create React App build creates empty folder

### ISSUE THREAD

**Issue by carapai** [developit/workerize-loader#72]
Building the app creates an empty folder while using workerize-loader

**Comment by gedion** [comment]
You probably have a webpack error in your worker file. The console.log hint below should be helpful.

https://github.com/facebook/create-react-app/issues/8014#issuecomment-557375996

**Comment by developit** [comment]
Indeed - this is a bug in CRA, so I'll close out this issue. Hopefully facebook/create-react-app#6286 gets merged soon!

**Comment by lbutler** [comment]
> You probably have a webpack error in your worker file. The console.log hint below should be helpful.
> 
> [facebook/create-react-app#8014 (comment)](https://github.com/facebook/create-react-app/issues/8014#issuecomment-557375996)

The above was helpful in figuring out what was wrong, if you want to avoid branching and ejecting, the error could be a simple ESLint warning as well.

In my case, the error was ESLint being upset with me using `self.postMessage()` within the worker file.

ESLint would provide the following error `Unexpected use of 'self'.eslint(no-restricted-globals)` in VSCode. When the CRA bug above is fixed it will show up in the console and fail the build and you won't spend a bunch of time trying to figure out why the build silently failed.

My temporary fix was to add disable the ESLint rule for my workerfile as I wasn't sure how to do it correctly...

```JS
/* eslint-disable no-restricted-globals */
```
