### ISSUE TITLE
Is it possible to use normal postMessage / messege listener behaviour?

### ISSUE THREAD

**Issue by xzilja** [developit/workerize-loader#78]
I was wondering if it is possible to utilise workerize for its async functions and also use `postMessage` inside of same worker? 

My particular use case is sort of state management. I define `store` and some `actions` in my worker. It also has `autorun` function that runs every time store is changed. I want to emit from this autorun function new value of the store that is within the worker.

On main thread I want to listen to this emit event and update sotre that is on the main thread with new value.

workerize makes it super easy to call my store actions, but in order to emit values I need to use "vanilla" worker approach. Hence this question. Is there a way to combine both of them in one worker file somehow?

**Comment by xzilja** [comment]
Well it seems as if `self.postMessage();` works within web worker and you can actually slap `addEventListener` on worker instance just fine as well.

However, `self.postMessage()` in typescript requires 2 arguments, data and something called `targetOrigin` (more about that second option available at https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) `targetOrigin` is a string and is used to prevent third parties from sniffing out data that web worker emits. When I add it I get error that reads:

> TypeError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': No function was found that matched the signature provided.

**Comment by developit** [comment]
@IljaDaderko use `self.postMessage('the message', '*')`.

**Comment by xzilja** [comment]
@developit ty for the tip, I added it, but this results in following error, without this argument it executes correctly.

> TypeError: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': No function was found that matched the signature provided.

**Comment by xzilja** [comment]
While this error still persists I was able to work around type error in typescript by adding 

`"lib": ["webworker"]`

to my tsconfig.json file and no longer need to specify second argument in `postMessage`, that solved my issue so I will close this one, but feel free to open it again if needed.
