### ISSUE TITLE
sourcemap is not propagated for worker file

### ISSUE THREAD

**Issue by rjgotten** [developit/workerize-loader#88]
If the source for the worker is treated by other loaders first, e.g. by Babel, then the sourcemap flowing out of those loaders is not propagated correctly by the rpc-worker-loader.

A minimal required and working change is trivial.
Instead of
```js
function rpcWorkerLoader(content) {
  return content + workerScript;
}
```

do
```js
function rpcWorkerLoader(content, sourcemap) {
  const cb = this.async();
  cb(null, content + workerScript, sourcemap);
}
```

Though technically, the new lines added by workerScript should be nulled away in the source map. (Webpack has source map helpers for this, iirc.)

**Comment by developit** [comment]
Released in [1.3.0](https://github.com/developit/workerize-loader/releases/tag/1.3.0).
