### ISSUE TITLE
Uncaught ReferenceError: addMethods is not defined

### ISSUE THREAD

**Issue by PfanP** [developit/workerize-loader#93]
Hi Gents.
I integrated workerize-loader with my app and it says "addMethods is not defined" in the blob file.
In worker.js file, it's replaced correctly but in blob file, there's no code included addMethods.

Here's the blob file.
`
(function() {
 var w = new Worker(URL.creatObjeccturl...)
addMethods(w, methods;
return w;
})(self)
`
Thanks

**Comment by developit** [comment]
Hi @self-coding-crab - are you able to show how you added `workerize-loader` to your webpack configuration or applied it to the module?

It seems like this would happen if your webpack configuration was somehow set up to ignore CommonJS require() statements.
