### ISSUE TITLE
IE11 - SCRIPT0: Syntax error

### ISSUE THREAD

**Issue by stanyq4** [developit/workerize-loader#95]
Does the library work with IE 11? 

I am getting the following error when trying to test with IE11:
```
SCRIPT0: Syntax error 
File: 3d577878351523fb68dd.worker.js, Line: 919, Column: 1
```

My worker setup is very minimal as it's shown in the demo.
`export.service.js`:

```
import worker from 'workerize-loader!./worker'

workerInstance.generateCsv(data).then((blob) => {
      // save generated blob to a file
      saveAs(blob, filename)
      resolve()
    }).catch((error) => {
      console.log('error: ', error)
      reject(error)
    })
```

`worker.js`:
```
export const generateCsv = async (data) => {
  // console.log('got here!!')
  if (!data) {
    return
  }

  const res = csvFormat(data)
  return new Blob([res], { type: 'text/csv;charset=utf-8;' })
}
```

**Comment by stanyq4** [comment]
The error occurs somewhere along thus lines:
```

addEventListener('message', e => {
    let {
        type,
        method,
        id,
        params
    } = e.data, f, p;
    if (type === 'RPC' && method) {
        if (f = __webpack_exports__[method]) {
            p = Promise.resolve().then(() => f.apply(__webpack_exports__, params));
        } else {
            p = Promise.reject('No such method');
        }
        p.then(result => {
            postMessage({
                type: 'RPC',
                id,
                result
            });
        }).catch(e => {
            let error = {
                message: e
            };
            if (e.stack) {
                error.message = e.message;
                error.stack = e.stack;
                error.name = e.name;
            }
            postMessage({
                type: 'RPC',
                id,
                error
            });
        });
    }
});
postMessage({
    type: 'RPC',
    method: 'ready'
});
```

**Comment by developit** [comment]
Ooof - good catch!  The untransformed `let` and destructuring syntax wasn't supposed to end up in `dist/rpc-worker-loader`.

**Comment by developit** [comment]
I'll get a release out shortly!

**Comment by stanyq4** [comment]
Thanks a ton! I'll test it out once it's released.

**Comment by yellott** [comment]
@developit  not sure if **browserslist** can work with target **node**, I had similar issue here https://github.com/developit/workerize-loader/pull/94

**Comment by developit** [comment]
This is fixed in [1.3.0](https://github.com/developit/workerize-loader/releases/tag/1.3.0).

**Comment by stanyq4** [comment]
The original issue is now resolved, seems like we are getting closer. 
However, IE11 still doesn't like the fact that `Promise` is used somewhere along the lines. 

I made the worker function as simple as possible but IE still throws the error: `'Promise' is undefined`

Attaching screenshot:

<img width="443" alt="Screen Shot 2020-06-17 at 2 07 30 PM" src="https://user-images.githubusercontent.com/23194864/84891215-3182c400-b0a4-11ea-8fa4-fb2aa6a29423.png">

**Comment by developit** [comment]
@stanyq4 you'll need to include a Promise polyfill in the worker module - not just for workerize, but also because Webpack itself requires it.

I'd recommend installing [promise-polyfill](https://www.npmjs.com/package/promise-polyfill), then importing it as the first line of your worker module:

```js
// my-worker.js
import 'promise-polyfill';

export const generateCsv = (data) => {
  console.log('doing work');
};
```

**Comment by stanyq4** [comment]
That worked, thank you again @developit 

Just FYI for others, you gotta use the following import syntax as described in docs:

`import 'promise-polyfill/src/polyfill';
`
or 
`import Promise from 'promise-polyfill';
`

**Comment by developit** [comment]
Awesome! I've just added that to the readme. 

I'd strongly recommend the first form (`import 'promise-polyfill/src/polyfill'`) since it allows webpack's chunk loading to access the polyfill too.
